### ISSUE TITLE
雷达图之间的宽度

### ISSUE THREAD

**Issue by xie3120** [qstumn/RadarChart#1]
没有设置雷达图之间的宽度的属性。

**Comment by qstumn** [comment]
之间的宽度是指？

**Comment by xie3120** [comment]
相邻多边形的之间的距离

**Comment by qstumn** [comment]
不好意思，还是不太理解你的意思，直接调整view的宽度不能满足你的需求么

**Comment by xie3120** [comment]
就拿圆来说吧，就是外层圆和相邻里层圆之间的距离。

**Comment by qstumn** [comment]
你是指各层之间的间距么？想改变这个属性有2种办法，可以setLayer指定的层数多一些，间距自然就小了。或者层数固定，View宽度高度变小，间距也就变小了。增大间距的话相反操作即可。
如果你不想各层之间等分间距，那暂时是办不到的。

**Comment by xie3120** [comment]
哦哦，我这边层数是固定的，想让各层之间的间距变大一些。
